spring.devtools.remote.restart.enabled=true
spring.devtools.livereload.enabled=true
update.scheduler.cron=0 0 * * * *
days.retained=20
readFeed.delete.scheduler.cron=0 30 * * * *
spring.config.import=optional:file:.env[.properties],classpath:news-classification.yml
qiita.ranking.scheduler.cron=0 15 * * * *
update.summary.scheduler.cron=0 5 * * * *
spring.profiles.active=develop
word.news.api.url=https://api.worldnewsapi.com
management.datadog.metrics.export.enabled=false
server.port=8080
server.ssl.key-store=keystore.p12
server.ssl.key-store-password=galewing
server.ssl.keyStoreType=PKCS12
server.ssl.keyAlias=tomcat
logging.charset.console=UTF-8
report.output.dir=output
logging.file.name=${LOG_FILE_PATH:./logs/alog.log}
ollama.model=gemma3:4b
update.feed.category.cron=0 40 * * * *
rsshub.base-url=http://localhost:3000
logging.level.reactor.netty.http.client=WARN
logging.level.reactor.netty.tcp=WARN
searxng.base-url=http://localhost:18080/search
trend.scheduler.cron=10 22 * * * *
translate.scheduler.cron=0 10 * * * *
